included:
  - Sources

excluded:
  - .build
  - build
  - poc
  - _bmad
  - _bmad-output

line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_comments: true

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 100
  error: 150

disabled_rules:
  - trailing_comma
  - opening_brace
  - identifier_name
  - type_name
  - nesting
  - force_cast
  - force_try
  - large_tuple
  - todo
  - for_where
  - cyclomatic_complexity
  - function_parameter_count
  - unused_closure_parameter

opt_in_rules:
  - empty_count
  - closure_spacing
